remote_theme: JS-DevTools/gh-pages-theme

title: Version Bump Prompt
logo: https://jsdevtools.org/img/logos/logo.png

author:
  twitter: JS_DevTools

google_analytics: UA-68102273-3

twitter:
  username: JS_DevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://jsdevtools.org/img/logos/card.png
  - scope:
      path: "test/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
